; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Profiles
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[dis][download][type] = ""
projects[dis][download][url] = ""
projects[dis][type] = "profile"

; Modules
projects[admin_menu][version] = "3.0-rc4"

projects[ctools][version] = "1.4"

projects[cck][version] = "3.0-alpha3"

projects[colorbox][version] = "2.5"

projects[context][version] = "3.2"

projects[copyright_block][version] = "2.2"

projects[features][version] = "2.0"

projects[follow][version] = "2.0-alpha1"

projects[libraries][version] = "2.2"

projects[omega_tools][version] = "3.0-rc4"

projects[strongarm][version] = "2.0"

projects[token][version] = "1.5"

projects[views][version] = "3.7"

projects[views_slideshow][version] = "3.1"

projects[webform][version] = "3.20"

; Themes
projects[omega][version] = "3.1"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[portfolio_base][download][type] = ""
projects[portfolio_base][download][url] = ""
projects[portfolio_base][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[portfolio_projects][download][type] = ""
projects[portfolio_projects][download][url] = ""
projects[portfolio_projects][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[portfolio_theme_feature][download][type] = ""
projects[portfolio_theme_feature][download][url] = ""
projects[portfolio_theme_feature][type] = "module"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[portfolio][download][type] = ""
projects[portfolio][download][url] = ""
projects[portfolio][type] = "theme"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[colorbox][download][type] = ""
libraries[colorbox][download][url] = ""
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

